# Discussion

We readily acknowledge several limitations of this study, particularly in the
survey design and methodology. The interviews were conducted as a convenience
sample rather than with a rigorous sampling strategy, with the statistical
caveats resulting from that design decision. The sample is also too small to
have substantial statistical power, particularly in statistics calculated on
multiple grouping dimensions. Finally, the survey collected self-reported
responses with no verification or validation of any kind.

Most survey responses were collected on fixed rail transit station platforms.
Passengers of UTA rail services were assumed to be the primary audience for the
microtransit service, and these riders were presumably more likely to be
available to complete a survey while waiting for a train. Additionally, UTA is
interested in supporting its fixed rail transit investments in the service area.
There is, however, no requirement that microtransit passengers use other UTA
services; data supplied by the microtransit provider but not included in this
study suggest that only 58\% percent of microtransit trips began or ended within
500 feet of a UTA rail transit station. This population might have preferences
or patterns that either match or contradict the initial findings of this
research.

A final limitation of these findings is the onset of the COVID-19 pandemic.
Government-imposed shutdowns and voluntary work stoppages related to the
pandemic did not begin in Utah until the week of March 15th, after data
collection for this project had completed. As such, the survey responses are
likely unaffected by changes in behavior related to the pandemic. However, the
pandemic has drastically affected the subsequent operations of both UTA and Via
and is likely to change many of the stated behaviors and attitudes reported in
this study. Many findings of this study will need to be reconsidered should
“normal” operations resume.

In discussing the responses to the question of what mode microtransit passengers
would have used were the service not available, we suggested there is anecdotal
evidence that commercial TNC rides are the primary competition. There are still
questions, however, of how use of this microtransit service might affect
conventional transit services. Table \@ref(tab:uta-ridership) shows the average
weekday ridership during November, December, and January for the period the
microtransit service was operating as well as the same three months in the two
prior years [uta2020boardings}. Total system ridership was remarkably stable
during these three periods. The microtransit service area -- in this case
defined by ridership on routes F514, 218, 526, F504, F518, F534, F546, and F547
-- was declining before the microtransit service began, though the decline
accelerated during the first three months of the service’s operation. By
comparison, the microtransit service carried approximately 316 passengers per
day during its first three months, more than compensating for the recent
observed decline in transit ridership were this to be identified as a major
contributing factor.

```{r uta-ridership}
ridership <- read_csv("data/UTA_Route-Level_Boardings%2C_Monthly_Counts.csv") 
lines <- c("F514", "218", "526", "F504", "F518", "F534", "F546", "F547")

rdf <- ridership %>% 
  mutate(
    date = lubridate::as_date(str_c(Year, Month, "01", sep = "-")),
    area = ifelse(LineAbbr %in% lines, "area", "other")
  ) %>%
  filter(ServiceType == "WKD") %>%
  filter(Month %in% c("November", "December", "January")) %>%
  mutate(
    period = ifelse( Month %in% c("November", "December"),  Year + 1, Year )
  ) %>%
  filter(period >= 2018) %>%
  group_by(period, area, LineAbbr) %>%
  summarise(AvgBoardings = mean(AvgBoardings)) %>%
  group_by(area, period) %>%
  summarise(br = sum(AvgBoardings)) %>%
  mutate(ch = (br - lag(br)) / lag(br) * 100) 

uta_ridership <- rdf %>%
    gather(key = count, value = value, -area, -period) %>%
    unite("key", area, count) %>%
    spread(key, value) %>%
    mutate(period =  c("2017-2018", "2018-2019", "2019-2020"))

if(knitr::is_latex_output()){
    kable(uta_ridership,
          col.names = c("Year", rep(c("Avg. Weekday Boardings", "% Change"), 2)), 
          digits = 2, caption = "Average Weekday Ridership, November through January",
          booktabs = TRUE, format = "latex") %>%
    add_header_above(c(" ", "Microtransit Service Area" = 2, "Other UTA Services" = 2))
} else {
    kable(uta_ridership,
          col.names = c("Year", rep(c("Avg. Weekday Boardings", "% Change"), 2)), 
          digits = 2, caption = "Average Weekday Ridership, November through January") %>%
    add_header_above(c(" ", "Microtransit Service Area" = 2, "Other UTA Services" = 2)) %>%
    kable_styling() 
}
```

In spite of these limitations, the findings of this research suggest potential
paths for transit agencies considering the deployment of a transportation mode
of this kind. First, the negative result with respect to income is somewhat
promising: an inability to reach out to low-income individuals was a factor in
the failure of Kutsusplus [@weckstrom2018]. The significant findings --- a
relationship with age in the original data and suggestive relationships with
also with household size and transit frequency --- also hold meaning for transit
providers. Of particular note is the absence of a middle ground or neutral
opinion on the service for the largest age group in the survey, those
individuals between 25 and 44 years old. In the next older group (45 to 64 years
old), a neutral opinion is considerably *overrepresented*. Does this mean
that members of this older group could be a target of successful marketing
efforts? How much of these attitudes are actually tied up in covarying household
conditions such as vehicle availability and household size? More research is
necessary.


## Conclusion

Microtransit services are regularly put forward as means to support last-mile /
first-mile trips on fixed route transit systems, and several such systems have
been deployed in the recent past. This paper presented initial findings from a
quick response survey aimed at learning who was most willing to use a new
service within weeks of the system launch. These initial findings suggest first
that younger adults are most willing to consider using microtransit services,
especially in larger households. Additionally, these services compete most
directly with commercial TNC ridehail offerings in addition to fixed-route
transit services.

Though preliminary, it is worth considering how these findings might transfer
to projects in other cities. The spatial and infrastructure context of the
region has played an important role in the UTA On-Demand's overall
success. A low-density but rapidly developing suburban region
bracketed by multiple high-frequency and high-capacity rail lines provides an 
ideal environment to test the potential of microtransit as a first-/last-mile 
access technology. The results of this study specifically suggest that younger
adults and those with larger households express a higher willingness to use
microtransit services. Salt Lake County and Utah more generally has a large
population that matches this description, with a high share of young adults and
a high birth rate relative to the United States average [@utahHealth]. Planners
considering implementing microtransit services to support station access might
consider the demographic characteristics of the population in their target areas
to maximize the project's success.

Transit passenger intercept surveys are an important method to determine who is
and who is not using a microtransit service, paired with demographic
characteristics and trip purpose information. To understand the rider
characteristics and trip purposes specifically of microtransit users, by
contrast, better survey methods are needed. In particular, a survey pushed
through the smartphone application used by the passengers would help in reaching
a considerably larger sample. It would also be theoretically possible in that
case for the researchers to pair the survey responses with actual observed trip
patterns for distinct users including origin, destination, and route GPS points,
regularity of use and variance in use patterns, and many other data variables.
Obtaining these data and conducting responsible research with them should be a
priority for the service operators and their agency partners.